n=int(input('insira um número: '))
a=13
print('-'*a)
print('{} * 01 = {}'.format(n,n*1))
print('-'*a)
print('{} * 02 = {}'.format(n,n*2))
print('-'*a)
print('{} * 03 = {}'.format(n,n*3))
print('-'*a)
print('{} * 04 = {}'.format(n,n*4))
print('-'*a)
print('{} * 05 = {}'.format(n,n*5))
print('-'*a)
print('{} * 06 = {}'.format(n,n*6))
print('-'*a)
print('{} * 07 = {}'.format(n,n*7))
print('-'*a)
print('{} * 08 = {}'.format(n,n*8))
print('-'*a)
print('{} * 09 = {}'.format(n,n*9))
print('-'*a)
print('{} * 10 = {}'.format(n,n*10))
print('-'*a)